<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EnhancedPlansSeeder extends Seeder
{
    /**
     * Run the database seeds for enhanced plans feature.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Enhanced Plans
        $plans = [
            [
                'id' => 1,
                'slug' => 'starter',
                'name' => 'Starter',
                'description' => 'Perfect for small teams getting started with HRIS',
                'short_description' => 'Essential features for small teams',
                'type' => 'package',
                'price_monthly' => 0,
                'price_yearly' => 0,
                'currency' => 'IDR',
                'features' => json_encode([
                    ['key' => 'gps_attendance', 'name' => 'GPS-based attendance validation', 'included' => true],
                    ['key' => 'employee_data', 'name' => 'Employee data management', 'included' => true, 'limit' => 'Up to 10 employees'],
                    ['key' => 'leave_requests', 'name' => 'Leave and time-off requests', 'included' => true],
                    ['key' => 'overtime_mgmt', 'name' => 'Overtime management', 'included' => true],
                    ['key' => 'basic_reporting', 'name' => 'Basic reporting', 'included' => true],
                    ['key' => 'email_support', 'name' => 'Email support', 'included' => true],
                ]),
                'feature_limits' => json_encode([
                    'max_employees' => 10,
                    'storage_gb' => 1,
                    'api_calls_per_month' => 1000
                ]),
                'max_users' => 10,
                'max_storage_gb' => 1,
                'is_recommended' => false,
                'is_popular' => false,
                'is_featured' => false,
                'button_text' => 'Current Plan',
                'button_variant' => 'outline',
                'show_monthly_price' => false,
                'show_yearly_price' => false,
                'trial_days' => 14,
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'slug' => 'lite',
                'name' => 'Lite',
                'description' => 'Ideal for growing teams needing advanced features',
                'short_description' => 'Advanced features for growing teams',
                'type' => 'package',
                'price_monthly' => 25000,
                'price_yearly' => 20000,
                'currency' => 'IDR',
                'features' => json_encode([
                    ['key' => 'all_starter', 'name' => 'All Starter features', 'included' => true],
                    ['key' => 'employee_data', 'name' => 'Employee data management', 'included' => true, 'limit' => 'Up to 50 employees'],
                    ['key' => 'attendance_settings', 'name' => 'Clock-in/out attendance settings', 'included' => true],
                    ['key' => 'document_mgmt', 'name' => 'Employee document management', 'included' => true],
                    ['key' => 'leave_settings', 'name' => 'Sick leave & time-out settings', 'included' => true],
                    ['key' => 'shift_mgmt', 'name' => 'Shift management', 'included' => true],
                    ['key' => 'advanced_reporting', 'name' => 'Advanced reporting', 'included' => true],
                    ['key' => 'mobile_app', 'name' => 'Mobile app access', 'included' => true],
                ]),
                'feature_limits' => json_encode([
                    'max_employees' => 50,
                    'storage_gb' => 10,
                    'api_calls_per_month' => 10000
                ]),
                'max_users' => 50,
                'max_storage_gb' => 10,
                'is_recommended' => true,
                'is_popular' => false,
                'is_featured' => true,
                'badge_text' => 'Recommended',
                'button_text' => 'Upgrade Plan',
                'button_variant' => 'primary',
                'yearly_discount_percent' => 20.00,
                'trial_days' => 14,
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'slug' => 'pro',
                'name' => 'Pro',
                'description' => 'For enterprises needing full control and customization',
                'short_description' => 'Enterprise-grade features and unlimited access',
                'type' => 'package',
                'price_monthly' => 75000,
                'price_yearly' => 70000,
                'currency' => 'IDR',
                'features' => json_encode([
                    ['key' => 'all_lite', 'name' => 'All Lite features', 'included' => true],
                    ['key' => 'employee_data', 'name' => 'Employee data management', 'included' => true, 'limit' => 'Unlimited employees'],
                    ['key' => 'api_access', 'name' => 'API access', 'included' => true],
                    ['key' => 'custom_integrations', 'name' => 'Custom integrations', 'included' => true],
                    ['key' => 'white_labeling', 'name' => 'White labeling', 'included' => true],
                    ['key' => 'dedicated_support', 'name' => 'Dedicated account manager', 'included' => true],
                    ['key' => 'phone_support', 'name' => '24/7 phone support', 'included' => true],
                    ['key' => 'advanced_analytics', 'name' => 'Advanced analytics', 'included' => true],
                    ['key' => 'sso_integration', 'name' => 'SSO integration', 'included' => true],
                ]),
                'feature_limits' => json_encode([
                    'max_employees' => null, // unlimited
                    'storage_gb' => 100,
                    'api_calls_per_month' => 100000
                ]),
                'max_users' => null,
                'max_storage_gb' => 100,
                'is_recommended' => false,
                'is_popular' => true,
                'is_featured' => true,
                'badge_text' => 'Most Popular',
                'button_text' => 'Upgrade Plan',
                'button_variant' => 'primary',
                'yearly_discount_percent' => 6.67,
                'trial_days' => 30,
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'slug' => 'standard-seat',
                'name' => 'Standard Seat',
                'description' => 'Basic access for individual team members',
                'short_description' => 'Per-seat pricing for basic access',
                'type' => 'seat',
                'price_per_seat' => 5000,
                'currency' => 'IDR',
                'features' => json_encode([
                    ['key' => 'time_tracking', 'name' => 'Basic time tracking', 'included' => true],
                    ['key' => 'personal_dashboard', 'name' => 'Personal dashboard', 'included' => true],
                    ['key' => 'leave_requests', 'name' => 'Leave requests', 'included' => true],
                    ['key' => 'email_support', 'name' => 'Email support', 'included' => true],
                    ['key' => 'mobile_app', 'name' => 'Mobile app access', 'included' => true],
                ]),
                'min_seats' => 1,
                'max_seats' => 100,
                'button_text' => 'Select Seats',
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'slug' => 'premium-seat',
                'name' => 'Premium Seat',
                'description' => 'Enhanced access with advanced features',
                'short_description' => 'Per-seat pricing with advanced features',
                'type' => 'seat',
                'price_per_seat' => 10000,
                'currency' => 'IDR',
                'features' => json_encode([
                    ['key' => 'all_standard', 'name' => 'All Standard features', 'included' => true],
                    ['key' => 'advanced_reporting', 'name' => 'Advanced reporting', 'included' => true],
                    ['key' => 'project_mgmt', 'name' => 'Project management', 'included' => true],
                    ['key' => 'priority_support', 'name' => 'Priority email support', 'included' => true],
                    ['key' => 'advanced_analytics', 'name' => 'Advanced analytics', 'included' => true],
                ]),
                'min_seats' => 1,
                'max_seats' => 100,
                'button_text' => 'Select Seats',
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'slug' => 'enterprise-seat',
                'name' => 'Enterprise Seat',
                'description' => 'Full feature access for power users and administrators',
                'short_description' => 'Complete per-seat access for power users',
                'type' => 'seat',
                'price_per_seat' => 15000,
                'currency' => 'IDR',
                'features' => json_encode([
                    ['key' => 'all_premium', 'name' => 'All Premium features', 'included' => true],
                    ['key' => 'full_access', 'name' => 'Full feature access', 'included' => true],
                    ['key' => 'dedicated_support', 'name' => 'Dedicated support', 'included' => true],
                    ['key' => 'custom_integrations', 'name' => 'Custom integrations', 'included' => true],
                    ['key' => 'api_access', 'name' => 'API access', 'included' => true],
                    ['key' => 'white_labeling', 'name' => 'White labeling', 'included' => true],
                    ['key' => 'advanced_security', 'name' => 'Advanced security', 'included' => true],
                    ['key' => 'phone_support', 'name' => '24/7 phone support', 'included' => true],
                ]),
                'min_seats' => 1,
                'max_seats' => null,
                'button_text' => 'Select Seats',
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('plans')->insert($plans);

        // Enhanced Payment Methods
        $paymentMethods = [
            [
                'id' => 1,
                'code' => 'visa',
                'name' => 'Visa',
                'type' => 'card',
                'provider' => 'Visa Inc.',
                'country_code' => 'ID',
                'logo_url' => '/img/payment/visa.svg',
                'color_primary' => '#1A1F71',
                'processing_fee_fixed' => 0,
                'processing_fee_percent' => 2.9,
                'min_amount' => 10000,
                'max_amount' => 50000000,
                'is_active' => true,
                'is_available_for_subscription' => true,
                'is_available_for_one_time' => true,
                'supported_currencies' => json_encode(['IDR', 'USD']),
                'processor' => 'stripe',
                'processing_time_hours' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'code' => 'mastercard',
                'name' => 'Mastercard',
                'type' => 'card',
                'provider' => 'Mastercard Inc.',
                'country_code' => 'ID',
                'logo_url' => '/img/payment/mastercard.svg',
                'color_primary' => '#EB001B',
                'processing_fee_fixed' => 0,
                'processing_fee_percent' => 2.9,
                'min_amount' => 10000,
                'max_amount' => 50000000,
                'is_active' => true,
                'is_available_for_subscription' => true,
                'is_available_for_one_time' => true,
                'supported_currencies' => json_encode(['IDR', 'USD']),
                'processor' => 'stripe',
                'processing_time_hours' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'code' => 'bca',
                'name' => 'Bank Central Asia (BCA)',
                'type' => 'bank',
                'provider' => 'PT Bank Central Asia Tbk',
                'country_code' => 'ID',
                'logo_url' => '/img/payment/bca.svg',
                'color_primary' => '#003399',
                'processing_fee_fixed' => 2500,
                'processing_fee_percent' => 0,
                'min_amount' => 10000,
                'max_amount' => 100000000,
                'is_active' => true,
                'is_available_for_subscription' => true,
                'is_available_for_one_time' => true,
                'supported_currencies' => json_encode(['IDR']),
                'processor' => 'midtrans',
                'processing_time_hours' => 24,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'code' => 'mandiri',
                'name' => 'Bank Mandiri',
                'type' => 'bank',
                'provider' => 'PT Bank Mandiri Tbk',
                'country_code' => 'ID',
                'logo_url' => '/img/payment/mandiri.svg',
                'color_primary' => '#FF8C00',
                'processing_fee_fixed' => 2500,
                'processing_fee_percent' => 0,
                'min_amount' => 10000,
                'max_amount' => 100000000,
                'is_active' => true,
                'is_available_for_subscription' => true,
                'is_available_for_one_time' => true,
                'supported_currencies' => json_encode(['IDR']),
                'processor' => 'midtrans',
                'processing_time_hours' => 24,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'code' => 'bni',
                'name' => 'Bank Negara Indonesia (BNI)',
                'type' => 'bank',
                'provider' => 'PT Bank Negara Indonesia Tbk',
                'country_code' => 'ID',
                'logo_url' => '/img/payment/bni.svg',
                'color_primary' => '#FF6900',
                'processing_fee_fixed' => 2500,
                'processing_fee_percent' => 0,
                'min_amount' => 10000,
                'max_amount' => 100000000,
                'is_active' => true,
                'is_available_for_subscription' => true,
                'is_available_for_one_time' => true,
                'supported_currencies' => json_encode(['IDR']),
                'processor' => 'midtrans',
                'processing_time_hours' => 24,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'code' => 'gopay',
                'name' => 'GoPay',
                'type' => 'digital_wallet',
                'provider' => 'PT Dompet Anak Bangsa',
                'country_code' => 'ID',
                'logo_url' => '/img/payment/gopay.svg',
                'color_primary' => '#00AA13',
                'processing_fee_fixed' => 1000,
                'processing_fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 20000000,
                'is_active' => true,
                'is_available_for_subscription' => true,
                'is_available_for_one_time' => true,
                'supported_currencies' => json_encode(['IDR']),
                'processor' => 'midtrans',
                'processing_time_hours' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'code' => 'dana',
                'name' => 'DANA',
                'type' => 'digital_wallet',
                'provider' => 'PT Espay Debit Indonesia Koe',
                'country_code' => 'ID',
                'logo_url' => '/img/payment/dana.svg',
                'color_primary' => '#118EEA',
                'processing_fee_fixed' => 1000,
                'processing_fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 20000000,
                'is_active' => true,
                'is_available_for_subscription' => true,
                'is_available_for_one_time' => true,
                'supported_currencies' => json_encode(['IDR']),
                'processor' => 'midtrans',
                'processing_time_hours' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'code' => 'ovo',
                'name' => 'OVO',
                'type' => 'digital_wallet',
                'provider' => 'PT Visionet Internasional',
                'country_code' => 'ID',
                'logo_url' => '/img/payment/ovo.svg',
                'color_primary' => '#4C2882',
                'processing_fee_fixed' => 1000,
                'processing_fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 20000000,
                'is_active' => true,
                'is_available_for_subscription' => true,
                'is_available_for_one_time' => true,
                'supported_currencies' => json_encode(['IDR']),
                'processor' => 'midtrans',
                'processing_time_hours' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('payment_methods')->insert($paymentMethods);

        // Create plan features for better management
        $planFeatures = [];
        $featureId = 1;

        foreach ($plans as $plan) {
            $features = json_decode($plan['features'], true);
            foreach ($features as $index => $feature) {
                $planFeatures[] = [
                    'id' => $featureId++,
                    'plan_id' => $plan['id'],
                    'feature_key' => $feature['key'],
                    'feature_name' => $feature['name'],
                    'feature_description' => $feature['description'] ?? null,
                    'is_included' => $feature['included'],
                    'limit_value' => $feature['limit'] ?? null,
                    'limit_type' => isset($feature['limit']) ? 'count' : null,
                    'sort_order' => $index + 1,
                    'is_highlighted' => in_array($feature['key'], ['all_starter', 'all_lite', 'all_premium']),
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }
        }

        // DB::table('plan_features')->insert($planFeatures);
    }
}
