// Configuration for pricing plans

import { Plan, SeatPlan, PaymentMethod } from './types';

export const PACKAGE_PLANS: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    description: 'Perfect for small teams getting started with HRIS',
    price: {
      monthly: 0,
      yearly: 0,
    },
    currency: 'USD',
    features: [
      { name: 'GPS-based attendance validation', included: true },
      { name: 'Employee data management', included: true, limit: 'Up to 10 employees' },
      { name: 'Leave and time-off requests', included: true },
      { name: 'Overtime management', included: true },
      { name: 'Fixed work schedule management', included: true },
      { name: 'Automatic salary calculation', included: true },
      { name: 'Basic reporting', included: true },
      { name: 'Email support', included: true },
      { name: 'Clock-in/out settings', included: false },
      { name: 'Document management', included: false },
      { name: 'Shift management', included: false },
      { name: 'API access', included: false },
      { name: 'Custom integrations', included: false },
      { name: 'Priority support', included: false },
    ],
    buttonText: 'Current Plan',
    buttonVariant: 'outline',
  },
  {
    id: 'lite',
    name: 'Lite',
    description: 'Ideal for growing teams needing advanced features',
    price: {
      monthly: 25000,
      yearly: 20000,
    },
    currency: 'IDR',
    features: [
      { name: 'All Starter features', included: true },
      { name: 'Employee data management', included: true, limit: 'Up to 50 employees' },
      { name: 'Clock-in/out attendance settings', included: true },
      { name: 'Employee document management', included: true },
      { name: 'Sick leave & time-out settings', included: true },
      { name: 'Shift management', included: true },
      { name: 'Site password protection', included: true },
      { name: 'Advanced reporting', included: true },
      { name: 'Priority email support', included: true },
      { name: 'Mobile app access', included: true },
      { name: 'API access', included: false },
      { name: 'Custom integrations', included: false },
      { name: 'Dedicated support', included: false },
      { name: 'White labeling', included: false },
    ],
    recommended: true,
    buttonText: 'Upgrade Plan',
    buttonVariant: 'primary',
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'For enterprises needing full control and customization',
    price: {
      monthly: 75000,
      yearly: 70000,
    },
    currency: 'IDR',
    features: [
      { name: 'All Lite features', included: true },
      { name: 'Employee data management', included: true, limit: 'Unlimited employees' },
      { name: 'Multiple projects', included: true, limit: 'Up to 5 projects' },
      { name: 'Client billing integration', included: true },
      { name: 'Free staging environment', included: true },
      { name: 'Code export functionality', included: true },
      { name: 'White labeling', included: true },
      { name: 'API access', included: true },
      { name: 'Custom integrations', included: true },
      { name: 'Dedicated account manager', included: true },
      { name: '24/7 phone support', included: true },
      { name: 'Advanced analytics', included: true },
      { name: 'Custom workflows', included: true },
      { name: 'SSO integration', included: true },
    ],
    popular: true,
    buttonText: 'Upgrade Plan',
    buttonVariant: 'primary',
  },
];

export const SEAT_PLANS: SeatPlan[] = [
  {
    id: 'standard-seat',
    name: 'Standard Seat',
    description: 'Basic access for individual team members',
    pricePerSeat: 5000,
    currency: 'IDR',
    minSeats: 1,
    maxSeats: 100,
    features: [
      { name: 'Basic time tracking', included: true },
      { name: 'Personal dashboard', included: true },
      { name: 'Leave requests', included: true },
      { name: 'Email support', included: true },
      { name: 'Mobile app access', included: true },
      { name: 'Basic reporting', included: false },
      { name: 'Advanced features', included: false },
      { name: 'Priority support', included: false },
    ],
    buttonText: 'Select Seats',
  },
  {
    id: 'premium-seat',
    name: 'Premium Seat',
    description: 'Enhanced access with advanced features',
    pricePerSeat: 10000,
    currency: 'IDR',
    minSeats: 1,
    maxSeats: 100,
    features: [
      { name: 'All Standard features', included: true },
      { name: 'Advanced reporting', included: true },
      { name: 'Project management', included: true },
      { name: 'Priority email support', included: true },
      { name: 'Advanced analytics', included: true },
      { name: 'Custom notifications', included: true },
      { name: 'API access', included: false },
      { name: 'White labeling', included: false },
    ],
    buttonText: 'Select Seats',
  },
  {
    id: 'enterprise-seat',
    name: 'Enterprise Seat',
    description: 'Full feature access for power users',
    pricePerSeat: 15000,
    currency: 'IDR',
    minSeats: 1,
    features: [
      { name: 'All Premium features', included: true },
      { name: 'Full feature access', included: true },
      { name: 'Dedicated support', included: true },
      { name: 'Custom integrations', included: true },
      { name: 'API access', included: true },
      { name: 'White labeling', included: true },
      { name: 'Advanced security', included: true },
      { name: '24/7 phone support', included: true },
    ],
    buttonText: 'Select Seats',
  },
];

export const PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: 'visa',
    name: 'Visa',
    type: 'card',
    logo: '/img/payment/visa.png',
  },
  {
    id: 'mastercard',
    name: 'Mastercard',
    type: 'card',
    logo: '/img/payment/mastercard.png',
  },
  {
    id: 'bca',
    name: 'Bank Central Asia (BCA)',
    type: 'bank',
    logo: '/img/payment/bca.png',
    processing_fee: 2500,
  },
  {
    id: 'mandiri',
    name: 'Bank Mandiri',
    type: 'bank',
    logo: '/img/payment/mandiri.png',
    processing_fee: 2500,
  },
  {
    id: 'bni',
    name: 'Bank Negara Indonesia (BNI)',
    type: 'bank',
    logo: '/img/payment/bni.png',
    processing_fee: 2500,
  },
  {
    id: 'gopay',
    name: 'GoPay',
    type: 'digital_wallet',
    logo: '/img/payment/gopay.png',
    processing_fee: 1000,
  },
  {
    id: 'dana',
    name: 'DANA',
    type: 'digital_wallet',
    logo: '/img/payment/dana.png',
    processing_fee: 1000,
  },
  {
    id: 'ovo',
    name: 'OVO',
    type: 'digital_wallet',
    logo: '/img/payment/ovo.png',
    processing_fee: 1000,
  },
];

export const CURRENCIES = {
  USD: { symbol: '$', name: 'US Dollar' },
  IDR: { symbol: 'Rp', name: 'Indonesian Rupiah' },
};

export const TAX_RATE = 0.11; // 11% VAT for Indonesia
